Pip 1358 use service account for compute
ENCODE-DCC/caper pull request #88
Opened 2020-09-04 22:04 UTC by leepc12

See https://encodedcc.atlassian.net/browse/PIP-1358 for details.

2020-09-14 08:02 UTC, ottojolanki requested changes
Looks good, some naming changes requested. I really like the exception reraising decorator!

2020-09-14 17:07 UTC, leepc12 commented on caper/caper_workflow_opts.py
> +                    'Docker image not found in WDL\'s metadata, which means that '
Done as you suggested. I am actually planning to replace all single-quotes with double-quotes in the next refactoring of the code.

2020-09-14 17:08 UTC, leepc12 commented on caper/cromwell_rest_api.py
> +def request_error_handler(func):
Done as you suggested.

2020-09-14 17:08 UTC, leepc12 commented on caper/cli.py
> +    kwargs = {
Fixed. Changed it to `args_from_cli`.

2020-09-15 06:37 UTC, ottojolanki approved these changes
LGTM

2020-09-15 16:15 UTC, merged